bypass agh

diff --git a/files/adguardhome b/files/adguardhome
--- a/files/adguardhome
+++ b/files/adguardhome
@@ -1,8 +1,21 @@
 #!/sbin/openrc-run
 
-command="/opt/AdGuardHome/AdGuardHome"
+acg_path="/opt/acg"
+
+# Load Configuration
+if [ -f "${acg_path}/files/acg-cfg" ]; then
+  . "${acg_path}/files/acg-cfg"
+else
+  echo "The configuration file is missing. Please re-run the installation script."
+  exit 1
+fi
+# Load Version
+. "${acg_path}/files/version"
+
+
+command="${acg_path}/scripts/clash-proxy"
 pidfile="/run/${RC_SVCNAME}.pid"
-command_args="-s run --pidfile ${pidfile} -w /opt/AdGuardHome"
+command_args="/opt/AdGuardHome/AdGuardHome -s run --pidfile ${pidfile} -w /opt/AdGuardHome"
 command_background=true
 name="AdGuard Home"
 description="Alpine Clash Gateway start-up script for OpenRC"
@@ -11,4 +24,9 @@ depend() {
 	need net
 	use dns
 }
+
+start_pre() {
+	${acg_path}/scripts/setup-cgroup-agh.sh
+}
+
 
